export const basePlayers = [
  "Abigail Vega",
  "Amy Bevan",
  "Andrea D'Elia",
  "Angela Riemann",
  "Anna Jaffe",
  "April Gambrell",
  "Arianna Marquez",
  "Azra Ramic",
  "Carissa Clarke",
  "Dawn Gregory",
  "Debbie McCallion",
  "Denise Jacobs",
  "Emilee Wallace",
  "Emily Shelton",
  "Eva Bukac",
  "Farhan Khan",
  "Hayley Bjerke",
  "Heather Ratliff",
  "Hope Grindlinger",
  "Jennifer Turnbull",
  "Jenny Evans",
  "Kathleen Campbell",
  "Katie Whittie",
  "Kelly Graham",
  "Kerry Blaney",
  "Krin Heinemann",
  "Kristine Smith",
  "Laura Hartman",
  "Lawrence Balerio",
  "Linda Montenegro",
  "Lyndsey Comment",
  "Melissa Miller",
  "Michaela Smith",
  "Michelle Czarnecki",
  "Nancy Horton",
  "Joemille Santiago",
  "Pam Sullivan",
  "Patty Montano",
  "Ryan Kendrick",
  "Stacey Harrison",
  "Stacey Knauer",
  "Stacy Heck",
  "Tandra Harvey",
  "Taylor Freeman",
  "Toni Walker",
  "Trista Serafin",
  "Vanessa Saucedo",
  "Whitney Evans",
  "Zach Marino",
  "Jenn Olsen",
];

export const giftsData = [
  { id: 1, name: "Blanket Hoodie", link: "https://www.amazon.com/dp/B0D9QP4HBZ/?coliid=I25AI7UFI4PAEF&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift1.jpg" },
  { id: 2, name: "Guess the Gibberish", link: "https://www.amazon.com/dp/B08BJCZ1MW/?coliid=I1JUMPOA9F6X6Q&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift2.jpg" },
  { id: 3, name: "The Let Them Theory", link: "https://www.amazon.com/dp/1401971369/?coliid=I9RM6X5U146JX&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift3.jpg" },
  { id: 4, name: "Screaming Chickens", link: "https://www.amazon.com/dp/B0CN1TZ2L8/?coliid=I2NVIRK861099R&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift4.jpg" },
  { id: 5, name: "Bop it!", link: "https://www.amazon.com/dp/B09JDMZ8X4/?coliid=I24D8G3X0PJBWO&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift5.jpg" },
  { id: 6, name: "Shower Steamers", link: "https://www.amazon.com/dp/B0BJYCRS51/?coliid=I3L1S9AWZ4VJWQ&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift6.jpg" },
  { id: 7, name: "I Should Have Known That", link: "https://www.amazon.com/dp/B0778TY7XP/?coliid=I1EU65I9V7BTH&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift7.jpg" },
  { id: 8, name: "$15 Starbucks Gift Card", link: "https://www.amazon.com/dp/B07KPLHM7L/?coliid=I2N3RD5I38YE67&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift8.jpg" },
  { id: 9, name: "Lindt Chocolates", link: "https://www.amazon.com/dp/B07WT6GP2F/?coliid=IBMNHKGTESC09&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift9.jpg" },
  { id: 10, name: "Packable Backpack", link: "https://www.amazon.com/dp/B078W43BTR/?coliid=I2A8SHH614ZZJR&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift10.jpg" },
  { id: 11, name: "6 Pack of Candles", link: "https://www.amazon.com/dp/B08XZ3HWF3/?coliid=I3MQB8LDWEU8FA&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift11.jpg" },
  { id: 12, name: "Movie Night Popcorn Set", link: "https://www.amazon.com/dp/B0B4X5SLKC/?coliid=INO7XBK5K3C4W&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift12.jpg" },
  { id: 13, name: "Fleece Blanket", link: "https://www.amazon.com/dp/B0B4X5SLKC/?coliid=INO7XBK5K3C4W&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift13.jpg" },
  { id: 14, name: "Bluetooth Speaker", link: "https://www.amazon.com/dp/B0B4X5SLKC/?coliid=INO7XBK5K3C4W&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift14.jpg" },
  { id: 15, name: "Wireless Charging Station", link: "https://www.amazon.com/dp/B0B4X5SLKC/?coliid=INO7XBK5K3C4W&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift15.jpg" },
  { id: 16, name: "Rechargable Hand Warmers", link: "https://www.amazon.com/dp/B0CHFDWF3L/?coliid=I3P5IKTCWRG3P1&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift16.jpg" },
  { id: 17, name: "Fidget Worm Toy", link: "https://www.amazon.com/dp/B0D311PH3P/?coliid=I2WXTGRKYSWTGF&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift17.jpg" },
  { id: 18, name: "$15 Amazon Giftcard", link: "https://www.amazon.com/dp/B0CDCJZL6P/?coliid=I353N7MS6XCKWK&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift18.jpg" },
  { id: 19, name: "Stemless Martini Glasses", link: "https://www.amazon.com/dp/B0F83V7XRN/?coliid=I2ETTVNIAA8L0W&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift19.jpg" },
  { id: 20, name: "Tell Me Without Telling Me", link: "https://www.amazon.com/dp/B0DTC25NBD/?coliid=I3EVOZ627AJ1OB&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift20.jpg" },
  { id: 21, name: "Yeti Water Bottle", link: "https://www.amazon.com/dp/B0CF726QR5/?coliid=I1L5IOB78CY78E&colid=3R102YN1ESL2V&psc=0&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift21.jpg" },
  { id: 22, name: "LED Work Light", link: "https://www.amazon.com/dp/B07G9X19G1/?coliid=I2WVCZT53NFH5T&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift22.jpg" },
  { id: 23, name: "Touch Lamp & Speaker", link: "https://www.amazon.com/dp/B01KPPOMUS/?coliid=I25QQIT2TW8VHQ&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift23.jpg" },
  { id: 24, name: "Positive Pickle Jar", link: "https://www.amazon.com/dp/B01KPPOMUS/?coliid=I25QQIT2TW8VHQ&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift24.jpg" },
  { id: 25, name: "Candle Warmer", link: "https://www.amazon.com/dp/B0FRLWC6X9/?coliid=I35QZGNJCZNW1J&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift25.jpg" },
  { id: 26, name: "Cube Brain Game", link: "https://www.amazon.com/dp/B07YSVBYHW/?coliid=I2I1T1L2ZDM0BT&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift26.jpg" },
  { id: 27, name: "Frother", link: "https://www.amazon.com/dp/B01LNFYCHM/?coliid=IN959XHN0SB4M&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift27.jpg" },
  { id: 28, name: "French Press", link: "https://www.amazon.com/dp/B01N78X92P/?coliid=I15VMCCJDHZ3HQ&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift28.jpg" },
  { id: 29, name: "Electric Salt & Pepper Grinder", link: "https://www.amazon.com/dp/B0BNPXX3TJ/?coliid=I6WURORUQYILZ&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift29.jpg" },
  { id: 30, name: "Lip Balm Set", link: "https://www.amazon.com/dp/B00DVYWOGA/?coliid=I120UHLK5748BN&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift30.jpg" },
  { id: 31, name: "Retro Bluetooth Speaker", link: "https://www.amazon.com/dp/B09XX8WH7W/?coliid=I13WOZ0HMDDGGE&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift31.jpg" },
  { id: 32, name: "Massage Gun", link: "https://www.amazon.com/dp/B0CP3K8G9X/?coliid=I7LO1CX10W1B&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift32.jpg" },
  { id: 33, name: "White Elephant Shirt", link: "https://www.amazon.com/dp/B07KRCGWHR/?coliid=I17SZS1XGZ8WF9&colid=3R102YN1ESL2V&psc=0&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift33.jpg" },
  { id: 34, name: "Pooping Pooches Calendar", link: "https://www.amazon.com/dp/B0754Y9GNH/?coliid=I1MM3LU2VR7M0Q&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift34.jpg" },
  { id: 35, name: "Rechargable Hand Warmers", link: "https://www.amazon.com/dp/B0CHFMK5DS/?coliid=I2W8W7OUMXQJBU&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift35.jpg" },
  { id: 36, name: "Dad Jokes Calendar", link: "https://www.amazon.com/dp/B0F2J1H2QV/?coliid=I1JCUMAJ9BRYCU&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift36.jpg" },
  { id: 37, name: "Chicken Shreader", link: "https://www.amazon.com/dp/B0DBQ57NN8/?coliid=IOZN2EO4YWRVW&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift37.jpg" },
  { id: 38, name: "Magsafe Phone Wallet", link: "https://www.amazon.com/dp/B0CPJDWCHW/?coliid=I13EQ0CDOLHT73&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift38.jpg" },
  { id: 39, name: "Salad Container", link: "https://www.amazon.com/dp/B0B247R9XB/?coliid=I13N5ZMQW9PQG8&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift39.jpg" },
  { id: 40, name: "Popcorn Maker", link: "https://www.amazon.com/dp/B0CBD2DST7/?coliid=I7YKW0J7GEQPV&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift40.jpg" },
  { id: 41, name: "Weighted Vest", link: "https://www.amazon.com/dp/B0F1TPCMJN/?coliid=I2O07EV53CWARD&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift41.jpg" },
  { id: 42, name: "Basket Organizer", link: "https://www.amazon.com/dp/B0FFLTD8FL/?coliid=I34WGWYSWJVSTQ&colid=3R102YN1ESL2V&psc=0&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift42.jpg" },
  { id: 43, name: "10lbs Kettle Bell", link: "https://www.amazon.com/dp/B07F1RGTRF/?coliid=I18AX32Z4Z4WXZ&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift43.jpg" },
  { id: 44, name: "Glass Tumbler", link: "https://www.amazon.com/dp/B0972S5PQV/?coliid=IDKRMR5IB54EC&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift44.jpg" },
  { id: 45, name: "Mug Warmer", link: "https://www.amazon.com/dp/B0FFN2T1RJ/?coliid=I3TMD3AHNL2NKN&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift45.jpg" },
  { id: 46, name: "Portable Blender", link: "https://www.amazon.com/dp/B0FV86BR5M/?coliid=I1ZS5LM70JUHAY&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift46.jpg" },
  { id: 47, name: "Tree Coasters", link: "https://www.amazon.com/dp/B0F9W7WYKR/?coliid=I13AXW9N41JOLN&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift47.jpg" },
  { id: 48, name: "Plant Terrarium", link: "https://www.amazon.com/dp/B07D29P5Z1/?coliid=I3QEDADYHSFP0I&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift48.jpg" },
  { id: 49, name: "Knot Decor", link: "https://www.amazon.com/dp/B0BBH5ZDP4/?coliid=I1TRVOB6SYR71H&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift49.jpg" },
  { id: 50, name: "Car Charger", link: "https://www.amazon.com/dp/B0D4215HCX/?coliid=I1Q587CIJZFVMT&colid=3R102YN1ESL2V&psc=1&ref_=list_c_wl_gv_vv_lig_pi_dp", imageFile: "gift50.jpg" },
];

export const totalGifts = giftsData.length;
