export const basePlayers = [
  "Aaron Cocks",
  "Alexis Dorr",
  "Alyssa Piselli",
  "Andy Espinoza",
  "Brian Corchiolo",
  "Carter Knight",
  "Cheyenne Scott",
  "Charles Niedringhaus",
  "Christopher Munden",
  "Christine Robinson",
  "Connor Parahus",
  "Francesca DiPlacido",
  "Gaston Soto",
  "Holly Milnes",
  "Jack Amsterdam",
  "Jen Barthelemy",
  "Jennifer Reshetar",
  "Joe Ogletree",
  "Justina Akpali",
  "Kaylee Richard",
  "Katrina Siske",
  "Kristen Mang",
  "Michael Duarte",
  "Myles Hohman",
  "Pam Jackson",
  "Phillip Ramirez",
  "Pieter Vandenburg",
  "Rachel Colletti",
  "Reeba Ivan",
  "Sabrina McGarrity",
  "Sara Meixner",
  "Sean Gibbons",
  "Shelby Montes de Oca",
  "Snow Vongsakulvong",
  "Tara Gartland",
  "Tammy Hill",
  "Vince Suriani",
];

export const giftsData = [
  { id: 1, name: "Bluetooth Speaker", link: "https://a.co/d/iANm6vx", imageFile: "gift1.jpg" },
  { id: 2, name: "Chair Heating Pad", link: "https://a.co/d/5ZEWLrB", imageFile: "gift2.jpg" },
  { id: 3, name: "Essential Oil Diffuser", link: "https://a.co/d/1AcVGT4", imageFile: "gift3.jpg" },
  { id: 4, name: "Glass Food Containers", link: "https://a.co/d/aIlPHu9", imageFile: "gift4.jpg" },
  { id: 5, name: "10oz Yeti Tumbler", link: "https://a.co/d/1BNWH5e", imageFile: "gift5.jpg" },
  { id: 6, name: "What Do You Meme?", link: "https://a.co/d/4gb0ptw", imageFile: "gift6.jpg" },
  { id: 7, name: "Fondue Pot", link: "https://a.co/d/hN0MCnV", imageFile: "gift7.jpg" },
  { id: 8, name: "Flower Pot", link: "https://a.co/d/e6z78ib", imageFile: "gift8.jpg" },
  { id: 9, name: "Door Sign", link: "https://a.co/d/g4AyxDK", imageFile: "gift9.jpg" },
  { id: 10, name: "Balsam & Cedar Candle", link: "https://a.co/d/4WzGaxD", imageFile: "gift10.jpg" },
  { id: 11, name: "Charcuterie Tray", link: "https://a.co/d/0NnLiq3", imageFile: "gift11.jpg" },
  { id: 12, name: "Catch Phrase", link: "https://a.co/d/3DazynN", imageFile: "gift12.jpg" },
  { id: 13, name: "Pickleball Set", link: "https://a.co/d/goKmJHb", imageFile: "gift13.jpg" },
  { id: 14, name: "Cocktail Shaker Set", link: "https://a.co/d/9aEy4ui", imageFile: "gift14.jpg" },
  { id: 15, name: "Coffee Javasok", link: "https://a.co/d/7lI6JDf", imageFile: "gift15.jpg" },
  { id: 16, name: "Mini Crockpot", link: "https://a.co/d/9rWBwJN", imageFile: "gift16.jpg" },
  { id: 17, name: "Stanley Wine Tumbler", link: "https://a.co/d/hD17Tis", imageFile: "gift17.jpg" },
  { id: 18, name: "3-in-1 Insulated Can Koozie", link: "https://a.co/d/a41SHmt", imageFile: "gift18.jpg" },
  { id: 19, name: "Massage Gun", link: "https://a.co/d/9XAfHhO", imageFile: "gift19.jpg" },
  { id: 20, name: "Smores Maker", link: "https://a.co/d/1EQmPRj", imageFile: "gift20.jpg" },
  { id: 21, name: "Electric Candle Lighters", link: "https://a.co/d/c2eoRrW", imageFile: "gift21.jpg" },
  { id: 22, name: "Popcorn Maker", link: "https://a.co/d/bwiwd4Z", imageFile: "gift22.jpg" },
  { id: 23, name: "Luggage Scales", link: "https://a.co/d/0Brj9p7", imageFile: "gift23.jpg" },
  { id: 24, name: "Lego Car", link: "https://a.co/d/8g8lF69", imageFile: "gift24.jpg" },
  { id: 25, name: "Tile Tracker", link: "https://a.co/d/6Zh6zQc", imageFile: "gift25.jpg" },
  { id: 26, name: "Carhartt Hat", link: "https://a.co/d/9fDMaAt", imageFile: "gift26.jpg" },
  { id: 27, name: "Blanket", link: "https://a.co/d/e6uYV0Y", imageFile: "gift27.jpg" },
  { id: 28, name: "Eagles Desk Pad", link: "https://a.co/d/6jI9AZP", imageFile: "gift28.jpg" },
  { id: 29, name: "Rechargable Hand Warmers", link: "https://a.co/d/cfOVzli", imageFile: "gift29.jpg" },
  { id: 30, name: "Himalayan Salt Lamp", link: "https://a.co/d/3pXu3BN", imageFile: "gift30.jpg" },
  { id: 31, name: "Holiday Waffle Maker", link: "https://a.co/d/2tw9nKI", imageFile: "gift31.jpg" },
  { id: 32, name: "Snoop Dogg Cookbook", link: "https://a.co/d/bhznkh1", imageFile: "gift32.jpg" },
  { id: 33, name: "Mug Warmer", link: "https://a.co/d/62gbzlk", imageFile: "gift33.jpg" },
  { id: 34, name: "Veggie Chopper & Slicer", link: "https://a.co/d/h0hbfOp", imageFile: "gift34.jpg" },
  { id: 35, name: "Mini Space Heater", link: "https://a.co/d/09FHrDm", imageFile: "gift35.jpg" },
  { id: 36, name: "40oz Water Bottle", link: "https://a.co/d/9Q4m4rF", imageFile: "gift36.jpg" },
  { id: 37, name: "Packing Cubes", link: "https://a.co/d/ejXOndu", imageFile: "gift37.jpg" },
];

export const totalGifts = giftsData.length;
